include: package:very_good_analysis/analysis_options.4.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/generated_plugin_registrant.dart"
    - "**/build/**"
    - "**/generated_*.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/l10n*.dart"
    - "**/*.gen.dart"
