name: yaho_coding_challenge
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  animations: ^2.0.7
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  device_preview: ^1.1.0
  dio: ^5.0.1
  dotted_line: ^3.1.0
  enum_to_string: ^2.0.1
  firebase_analytics: ^10.1.4
  firebase_app_installations: ^0.2.1+12
  firebase_core: ^2.7.0
  firebase_crashlytics: ^3.0.15
  firebase_dynamic_links: ^5.0.15
  firebase_messaging: ^14.4.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.2
  freezed_annotation: ^2.2.0
  gap: ^2.0.1
  geolocator: ^9.0.2
  go_router: ^6.2.0
  google_maps_flutter: ^2.2.4
  hive: ^2.2.3
  hooks_riverpod: ^2.3.0
  image_picker: ^0.8.6+4
  intl: ^0.17.0
  json_annotation: ^4.8.0
  local_auth: ^2.1.6
  logging: ^1.1.1
  permission_handler: ^10.2.0
  pin_code_fields: ^7.4.0
  retrofit: ^4.0.1
  riverpod_annotation: ^2.0.0
  shared_preferences: ^2.0.18
  shimmer: ^2.0.0
  url_launcher: ^6.1.10
  web_socket_channel: ^2.3.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  go_router_builder: ^1.1.6
  json_serializable: ^6.6.1
  mockito: ^5.3.2
  # mocktail: ^0.3.0
  retrofit_generator: ^5.0.0
  riverpod_generator: ^2.0.0
  test: ^1.22.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/Montserrat/
    - assets/svg/
    - assets/svg/feather/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700

flutter_gen:
  output: lib/src/gen/
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
