// Mocks generated by Mockito 5.3.2 from annotations
// in yaho_coding_challenge/test/page/root_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:yaho_coding_challenge/src/data/model/user_response.dart' as _i2;
import 'package:yaho_coding_challenge/src/data/repository/user_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserResponse_0 extends _i1.SmartFake implements _i2.UserResponse {
  _FakeUserResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i3.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserResponse> getUser(int? page) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [page],
        ),
        returnValue: _i4.Future<_i2.UserResponse>.value(_FakeUserResponse_0(
          this,
          Invocation.method(
            #getUser,
            [page],
          ),
        )),
      ) as _i4.Future<_i2.UserResponse>);
}
